version: "3.8"
services: 
    redis_server:
        image: redis:latest
        #restart: always
        container_name: "compose-redis"
        ports: 
            - "6379:6379"
        volumes:
            - "$PWD/redis_data:/data:rw"
        command:
            - /bin/sh
            - -c
            - "cd /data && redis-server --appendonly yes"
        networks:
            - app_net
networks:
    app_net:
