DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS friend;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(40) UNIQUE NOT NULL,
    sex VARCHAR(10) NOT NULL DEFAULT 'male',
    birthdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password TEXT NOT NULL,
    request_ip VARCHAR(20) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE friend (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    sorted_key VARCHAR(255) UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id, friend_id) REFERENCES user (id, id)
);
